---
title: C28125
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
author: corob-msft
ms.author: corob
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 3b4d55d905208b1b05610aaae91806dc9a44562e
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 02/15/2020
ms.locfileid: "77264265"
---
# <a name="c28125"></a>C28125
Warnung C28125: Die Funktion muss innerhalb eines try/except-Blocks aufgerufen werden.

 Der Treiber ruft eine Funktion auf, die innerhalb eines try/with-Blocks aufgerufen werden muss, z. b. [Probe forread](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforread), [probeforwrite](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforwrite), [MmProbeAndLockPages](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-mmprobeandlockpages).

## <a name="example"></a>Beispiel
 Im folgenden Codebeispiel wird diese Warnung generiert:

```cpp
ProbeForRead(addr, len, 4);
```

 Im folgenden Codebeispiel wird diese Warnung vermieden:

```cpp
__try
{
    ProbeForRead(addr, len, 4);
}
__except(EXCEPTION_EXECUTE_HANDLER)
{
    Status = GetExceptionCode();
    ... report error status
}
```
